<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite" duration-ms="9433" started-at="2014-12-29T12:23:32Z" finished-at="2014-12-29T12:23:41Z">
    <groups>
    </groups>
    <test name="test1" duration-ms="9393" started-at="2014-12-29T12:23:32Z" finished-at="2014-12-29T12:23:41Z">
      <class name="Scripts.AppTest">
        <test-method status="PASS" signature="InitilizeDriver()[pri:0, instance:Scripts.AppTest@63709dc6]" name="InitilizeDriver" is-config="true" duration-ms="5785" started-at="2014-12-29T17:53:32Z" finished-at="2014-12-29T17:53:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitilizeDriver -->
        <test-method status="FAIL" signature="AppTestDemo()[pri:0, instance:Scripts.AppTest@63709dc6]" name="AppTestDemo" duration-ms="3246" started-at="2014-12-29T17:53:38Z" finished-at="2014-12-29T17:53:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Google] but found [Google1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Google] but found [Google1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Scripts.AppTest.AppTestDemo(AppTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AppTestDemo -->
        <test-method status="PASS" signature="ClosedDriver()[pri:0, instance:Scripts.AppTest@63709dc6]" name="ClosedDriver" is-config="true" duration-ms="343" started-at="2014-12-29T17:53:41Z" finished-at="2014-12-29T17:53:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClosedDriver -->
      </class> <!-- Scripts.AppTest -->
    </test> <!-- test1 -->
    <test name="test2" duration-ms="3" started-at="2014-12-29T12:23:41Z" finished-at="2014-12-29T12:23:41Z">
      <class name="Scripts.GoogleTest">
        <test-method status="PASS" signature="MyGoogleDemo()[pri:0, instance:Scripts.GoogleTest@2c35ff78]" name="MyGoogleDemo" duration-ms="1" started-at="2014-12-29T17:53:41Z" finished-at="2014-12-29T17:53:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MyGoogleDemo -->
      </class> <!-- Scripts.GoogleTest -->
    </test> <!-- test2 -->
    <test name="test3" duration-ms="4" started-at="2014-12-29T12:23:41Z" finished-at="2014-12-29T12:23:41Z">
      <class name="Scripts.TestClass">
        <test-method status="SKIP" signature="SampleTest()[pri:0, instance:Scripts.TestClass@37ea14c3]" name="SampleTest" duration-ms="1" started-at="2014-12-29T17:53:41Z" finished-at="2014-12-29T17:53:41Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Using HSQL will fail this test. aborting...]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Using HSQL will fail this test. aborting...
	at Scripts.TestClass.SampleTest(TestClass.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SampleTest -->
      </class> <!-- Scripts.TestClass -->
    </test> <!-- test3 -->
  </suite> <!-- TestSuite -->
</testng-results>
